-- Generated by Envision Gui2Lua, VER-1, 0-18.

local Instances = {
	Main = Instance.new("ScreenGui"),
	MainGUI = Instance.new("Frame"),
	Nameless = Instance.new("TextButton"),
	ChatBypass = Instance.new("TextButton"),
	MoreUNC = Instance.new("TextButton"),
	Title = Instance.new("TextLabel"),
}

Instances.Main.Name = "Main"
Instances.Main.Parent = game.Players.LocalPlayer.PlayerGui
Instances.Main.ResetOnSpawn = false

Instances.MainGUI.Name = "MainGUI"
Instances.MainGUI.Parent = Instances.Main
Instances.MainGUI.Size = UDim2.new(0, 492, 0, 271)
Instances.MainGUI.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.MainGUI.Position = UDim2.new(0.300727576, 0, 0.282747597, 0)
Instances.MainGUI.BorderSizePixel = 0
Instances.MainGUI.BackgroundColor3 = Color3.fromRGB(170, 0, 0)

Instances.Nameless.Name = "Nameless"
Instances.Nameless.Parent = Instances.MainGUI
Instances.Nameless.Size = UDim2.new(0, 162, 0, 23)
Instances.Nameless.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Nameless.Position = UDim2.new(0.024390243, 0, 0.457564563, 0)
Instances.Nameless.BorderSizePixel = 0
Instances.Nameless.BackgroundColor3 = Color3.fromRGB(170, 85, 1)
Instances.Nameless.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.Nameless.Text = "FeBypass Nameless Admin"
Instances.Nameless.TextSize = 14
Instances.Nameless.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.Nameless.MouseButton1Down:Connect(function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/FD2Team/Nameless-Admin-No-Byfron-Kick/main/Source",true))()
end)

Instances.ChatBypass.Name = "ChatBypass"
Instances.ChatBypass.Parent = Instances.MainGUI
Instances.ChatBypass.Size = UDim2.new(0, 151, 0, 23)
Instances.ChatBypass.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.ChatBypass.Position = UDim2.new(0.376016259, 0, 0.457564563, 0)
Instances.ChatBypass.BorderSizePixel = 0
Instances.ChatBypass.BackgroundColor3 = Color3.fromRGB(170, 85, 0)
Instances.ChatBypass.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.ChatBypass.Text = "Fe ChatBypass"
Instances.ChatBypass.TextSize = 14
Instances.ChatBypass.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.ChatBypass.MouseButton1Down:Connect(function()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/Clickgameplay/no-tag-script/main/.NoTagScript"))()
end)

Instances.MoreUNC.Name = "MoreUNC"
Instances.MoreUNC.Parent = Instances.MainGUI
Instances.MoreUNC.Size = UDim2.new(0, 141, 0, 23)
Instances.MoreUNC.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.MoreUNC.Position = UDim2.new(0.697154462, 0, 0.457564563, 0)
Instances.MoreUNC.BorderSizePixel = 0
Instances.MoreUNC.BackgroundColor3 = Color3.fromRGB(170, 85, 1)
Instances.MoreUNC.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.MoreUNC.Text = "MoreUNC"
Instances.MoreUNC.TextSize = 14
Instances.MoreUNC.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
Instances.MoreUNC.MouseButton1Down:Connect(function()
	loadstring(game:HttpGet('https://pastebin.com/raw/JPw0jeLZ'))()
end)

Instances.Title.Name = "Title"
Instances.Title.Parent = Instances.MainGUI
Instances.Title.Size = UDim2.new(0, 492, 0, 16)
Instances.Title.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Title.BorderSizePixel = 0
Instances.Title.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
Instances.Title.TextColor3 = Color3.fromRGB(0, 0, 0)
Instances.Title.Text = "Touseef's ScriptHub"
Instances.Title.TextSize = 14
Instances.Title.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)


local UserInputService = game:GetService("UserInputService")

local gui = Instances.MainGUI

local dragging
local dragInput
local dragStart
local startPos

local function update(input)
	local delta = input.Position - dragStart
	gui.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
end

gui.InputBegan:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
		dragging = true
		dragStart = input.Position
		startPos = gui.Position

		input.Changed:Connect(function()
			if input.UserInputState == Enum.UserInputState.End then
				dragging = false
			end
		end)
	end
end)

gui.InputChanged:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
		dragInput = input
	end
end)

UserInputService.InputChanged:Connect(function(input)
	if input == dragInput and dragging then
		update(input)
	end
end)

--[[ End of generation. ]]
