local Miss = game:GetService("ReplicatedStorage").Assets.Emotes._MissTheQuiet
local Silly = game:GetService("ReplicatedStorage").Assets.Emotes._SillyBilly
local Subterfuge = game:GetService("ReplicatedStorage").Assets.Emotes._Subterfuge
local NoliRework = game:GetService("ReplicatedStorage").Assets.Killers["!NoliRework"].Config
local Noli = game:GetService("ReplicatedStorage").Assets.Killers["!Noli"].Config
local ZombieKing = game:GetService("ReplicatedStorage").Assets.Killers["!ZombieKing"].Config
local Jeff = game:GetService("ReplicatedStorage").Assets.Killers["!JeffTheKiller"].Config
local SixSixSix = game:GetService("ReplicatedStorage").Assets.Killers["!Guest666"].Config
local Bonk = game:GetService("ReplicatedStorage").Assets.Killers["!BonkBoy"].Config
local BusterBrawel = game:GetService("ReplicatedStorage").Assets.Killers["!BusterBrawler"].Config
local Duke = game:GetService("ReplicatedStorage").Assets.Killers["!DukeErisia"].Config
local EriKing = game:GetService("ReplicatedStorage").Assets.Killers["!Erlking"].Config
local Sancho = game:GetService("ReplicatedStorage").Assets.Killers["!Sancho"].Config
local Slenderman = game:GetService("ReplicatedStorage").Assets.Killers["!Slenderman"].Config
local SolemnLament = game:GetService("ReplicatedStorage").Assets.Killers["!SolemnLament"].Config
local Stalker = game:GetService("ReplicatedStorage").Assets.Killers["!Stalker"].Config
local Sukuna = game:GetService("ReplicatedStorage").Assets.Killers["!SukunaKiller"].Config
local Quiet = require(Miss)
local Subter = require(Subterfuge)
local Billy = require(Silly)
local n = require(Noli)
local nr = require(NoliRework)
local k = require(King)
local zk = require(ZombieKing)
local j = require(Jeff)
local six = require(SixSixSix)
local Boy = require(Bonk)
local bb = require(BusterBrawel)
local d = require(Duke)
local ek = require(EriKing)
local s = require(Sancho)
local sm = require(Slenderman)
local sl = require(SolemnLament)
local sr = require(Stalker)
local sn = require(Sukuna)
Boy.Exclusive = false;
bb.Exclusive = false;
d.Exclusive = false;
ek.Exclusive = false;
s.Exclusive = false;
sm.Exclusive = false;
sl.Exclusive = false;
sr.Exclusive = false;
sn.Exclusive = false;
Quiet.Exclusive = false;
Subter.Exclusive = false;
Billy.Exclusive = false;
n.Exclusive = false;
nr.Exclusive = false;
zk.Exclusive = false;
j.Exclusive = false;
six.Exclusive = false;
