local Miss = game:GetService("ReplicatedStorage").Assets.Emotes._MissTheQuiet
local Silly = game:GetService("ReplicatedStorage").Assets.Emotes._SillyBilly
local Subterfuge = game:GetService("ReplicatedStorage").Assets.Emotes._Subterfuge
local NoliRework = game:GetService("ReplicatedStorage").Assets.Killers["!NoliRework"].Config
local Noli = game:GetService("ReplicatedStorage").Assets.Killers["!Noli"].Config
local ZombieKing = game:GetService("ReplicatedStorage").Assets.Killers["!ZombieKing"].Config
local Jeff = game:GetService("ReplicatedStorage").Assets.Killers["!JeffTheKiller"].Config
local SixSixSix = game:GetService("ReplicatedStorage").Assets.Killers["!Guest666"].Config
local Quiet = require(Miss)
local Subter = require(Subterfuge)
local Billy = require(Silly)
local n = require(Noli)
local nr = require(NoliRework)
local zk = require(ZombieKing)
local j = require(Jeff)
local six = require(SixSixSix)
Quiet.Exclusive = false;
Subter.Exclusive = false;
Billy.Exclusive = false;
n.Exclusive = false;
nr.Exclusive = false;
zk.Exclusive = false;
j.Exclusive = false;
six.Exclusive = false;
